/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsWhitelistRouteImport } from './routes/settings.whitelist'
import { Route as SettingsCleanupRouteImport } from './routes/settings.cleanup'
import { Route as SettingsBlacklistRouteImport } from './routes/settings.blacklist'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWhitelistRoute = SettingsWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCleanupRoute = SettingsCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBlacklistRoute = SettingsBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/blacklist': typeof SettingsBlacklistRoute
  '/settings/cleanup': typeof SettingsCleanupRoute
  '/settings/whitelist': typeof SettingsWhitelistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/blacklist': typeof SettingsBlacklistRoute
  '/settings/cleanup': typeof SettingsCleanupRoute
  '/settings/whitelist': typeof SettingsWhitelistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/blacklist': typeof SettingsBlacklistRoute
  '/settings/cleanup': typeof SettingsCleanupRoute
  '/settings/whitelist': typeof SettingsWhitelistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/blacklist'
    | '/settings/cleanup'
    | '/settings/whitelist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/blacklist'
    | '/settings/cleanup'
    | '/settings/whitelist'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/blacklist'
    | '/settings/cleanup'
    | '/settings/whitelist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/whitelist': {
      id: '/settings/whitelist'
      path: '/whitelist'
      fullPath: '/settings/whitelist'
      preLoaderRoute: typeof SettingsWhitelistRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cleanup': {
      id: '/settings/cleanup'
      path: '/cleanup'
      fullPath: '/settings/cleanup'
      preLoaderRoute: typeof SettingsCleanupRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/blacklist': {
      id: '/settings/blacklist'
      path: '/blacklist'
      fullPath: '/settings/blacklist'
      preLoaderRoute: typeof SettingsBlacklistRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsBlacklistRoute: typeof SettingsBlacklistRoute
  SettingsCleanupRoute: typeof SettingsCleanupRoute
  SettingsWhitelistRoute: typeof SettingsWhitelistRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBlacklistRoute: SettingsBlacklistRoute,
  SettingsCleanupRoute: SettingsCleanupRoute,
  SettingsWhitelistRoute: SettingsWhitelistRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
